// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJJUQvv9kKpytJ08Kk04KuNLzgmYMS90',
    appId: '1:972091484849:web:3b444efca9394ceddf9090',
    messagingSenderId: '972091484849',
    projectId: 'doto-d5425',
    authDomain: 'doto-d5425.firebaseapp.com',
    storageBucket: 'doto-d5425.appspot.com',
    measurementId: 'G-PNQM2535G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTm-hpOX9M4ZAH53-A72tUWmqI1cOauz8',
    appId: '1:972091484849:android:aa55118523961dbedf9090',
    messagingSenderId: '972091484849',
    projectId: 'doto-d5425',
    storageBucket: 'doto-d5425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAkbcUZQxcTwcW5jqv7vD6AmiK9miRWg',
    appId: '1:972091484849:ios:72ceea0870f2b121df9090',
    messagingSenderId: '972091484849',
    projectId: 'doto-d5425',
    storageBucket: 'doto-d5425.appspot.com',
    iosBundleId: 'com.example.todoWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAkbcUZQxcTwcW5jqv7vD6AmiK9miRWg',
    appId: '1:972091484849:ios:72ceea0870f2b121df9090',
    messagingSenderId: '972091484849',
    projectId: 'doto-d5425',
    storageBucket: 'doto-d5425.appspot.com',
    iosBundleId: 'com.example.todoWithFirebase',
  );
}
